"""Generate parser/unicode_tables.mbt: the Python `str` character predicates
(`isalpha`, `isdigit`, `isspace`, `isdecimal` + digit value) and the simple
`str.lower()` mapping, used by the parser to tokenize and look up words
exactly like CPython does.

Run: python3 tools/gen_parser_unicode.py > parser/unicode_tables.mbt
"""
import sys
import unicodedata


def ranges(pred):
    out = []
    start = None
    for c in range(0x110000):
        p = pred(chr(c))
        if p and start is None:
            start = c
        if not p and start is not None:
            out.append((start, c - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def enc_ranges(rs):
    parts = []
    for a, b in rs:
        parts.append('%x' % a if a == b else '%x-%x' % (a, b))
    return parts


def chunk(parts, width=70):
    lines = []
    cur = ''
    for p in parts:
        if cur and len(cur) + 1 + len(p) > width:
            lines.append(cur)
            cur = p
        else:
            cur = p if not cur else cur + ' ' + p
    if cur:
        lines.append(cur)
    return lines


def emit_string(name, doc, parts):
    print('///|')
    print('/// %s' % doc)
    print('let %s : String =' % name)
    for line in chunk(parts):
        print('  #|%s' % line)
    print()


# Decimal digits: every Nd run must start at a zero so that the digit value
# is (c - start) % 10.
dec = ranges(str.isdecimal)
for a, b in dec:
    for c in range(a, b + 1):
        assert unicodedata.decimal(chr(c)) == (c - a) % 10, hex(c)

# Simple lowercase mapping (single code point results), as runs of
# (start, end, step, delta).
single = []
multi = {}
for c in range(0x110000):
    lo = chr(c).lower()
    if lo == chr(c):
        continue
    if len(lo) == 1:
        single.append((c, ord(lo) - c))
    else:
        multi[c] = lo
runs = []
for c, d in single:
    if runs:
        s, e, step, delta = runs[-1]
        if delta == d and (step == 0 and c - e in (1, 2) or step and c - e == step):
            runs[-1] = (s, c, c - e, delta)
            continue
    runs.append((c, c, 0, d))
lower_parts = ['%x:%x:%d:%d' % (s, e, step or 1, d) for s, e, step, d in runs]
assert list(multi) == [0x130], multi

print('// Generated by tools/gen_parser_unicode.py from Python %s (Unicode %s);'
      % (sys.version.split()[0], unicodedata.unidata_version))
print('// do not edit.')
print()
emit_string('alpha_ranges_src', 'Code points for which `str.isalpha()` is true.',
            enc_ranges(ranges(str.isalpha)))
emit_string('digit_ranges_src', 'Code points for which `str.isdigit()` is true.',
            enc_ranges(ranges(str.isdigit)))
emit_string('space_ranges_src', 'Code points for which `str.isspace()` is true.',
            enc_ranges(ranges(str.isspace)))
emit_string('decimal_ranges_src',
            'Code points for which `str.isdecimal()` is true; each run starts at a zero.',
            enc_ranges(dec))
emit_string('lower_runs_src',
            '`str.lower()` single-code-point mappings as `start:end:step:delta` runs\n'
            '/// (U+0130 maps to two code points and is special-cased).',
            lower_parts)
