"""Generate relativedelta/python_corpus_test.mbt from the reference
python-dateutil relativedelta (vendored in .repos/dateutil).

Run: python3 tools/gen_relativedelta_corpus.py > relativedelta/python_corpus_test.mbt
"""
import os
import random
import sys
from datetime import date, datetime, timedelta

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path[:0] = [os.path.join(ROOT, 'tools', 'pyshim'),
                os.path.join(ROOT, '.repos', 'dateutil', 'src'),
                os.path.join(ROOT, '.repos', 'dateutil')]

from dateutil import tz  # noqa: E402
from dateutil.relativedelta import relativedelta, weekdays  # noqa: E402

rnd = random.Random(20261001)
out = ['// Generated by tools/gen_relativedelta_corpus.py from python-dateutil; do not edit.\n']

WD = ['mo', 'tu', 'we', 'th', 'fr', 'sa', 'su']


def mbt_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def fl(v):
    r = repr(float(v))
    if 'e' in r:
        m, e = r.split('e')
        if '.' not in m:
            m += '.0'
        r = m + 'e' + e
    return r


def emit(name, lines):
    out.append('///|\ntest "%s" {\n%s\n}\n' % (name, '\n'.join('  ' + l for l in lines)))


def outcome(f):
    try:
        r = f()
    except (ValueError, OverflowError) as e:
        return type(e).__name__ if not isinstance(e, ValueError) else 'ValueError'
    return repr(r)


# ---------------------------------------------------------------------------
# random relativedeltas


def rand_weekday():
    k = rnd.randrange(7)
    n = rnd.choice([None, None, 0, 1, -1, 2, -2, 3, -3, 5, -5])
    py = weekdays[k](n)
    if n is None:
        mb = '@relativedelta.%s' % WD[k]
    else:
        mb = '@relativedelta.%s.nth(Some(%d))' % (WD[k], n)
    return py, mb


def rand_rd(floaty=None, allow_yearday=True):
    """Return (python relativedelta or exception name, MoonBit constructor)."""
    if floaty is None:
        floaty = rnd.random() < 0.35
    kw = {}
    mb = []
    if rnd.random() < 0.5:
        kw['years'] = rnd.choice([rnd.randint(-3, 3), rnd.randint(-300, 300)])
    if rnd.random() < 0.5:
        kw['months'] = rnd.choice([rnd.randint(-13, 13), rnd.randint(-400, 400)])
    for k, lo, hi in [('days', -400, 400), ('weeks', -60, 60), ('hours', -50, 50),
                      ('minutes', -200, 200), ('seconds', -5000, 5000),
                      ('microseconds', -3000000, 3000000)]:
        if rnd.random() < 0.3:
            if floaty and rnd.random() < 0.7:
                kw[k] = round(rnd.uniform(lo, hi) / rnd.choice([1, 7, 30]), rnd.choice([1, 2, 3, 6]))
            else:
                kw[k] = rnd.randint(lo, hi)
    if rnd.random() < 0.15:
        kw['leapdays'] = rnd.choice([-1, 1, 2])
    for k, vals in [('year', lambda: rnd.choice([0, rnd.randint(1, 9999), rnd.randint(1990, 2030)])),
                    ('month', lambda: rnd.choice([0, rnd.randint(1, 12), rnd.randint(1, 12)])),
                    ('day', lambda: rnd.choice([0, -1, rnd.randint(1, 31), rnd.randint(28, 31)])),
                    ('hour', lambda: rnd.randint(0, 23)),
                    ('minute', lambda: rnd.randint(0, 59)),
                    ('second', lambda: rnd.randint(0, 59)),
                    ('microsecond', lambda: rnd.randint(0, 999999))]:
        if rnd.random() < 0.12:
            kw[k] = vals()
    wd_mb = None
    if rnd.random() < 0.3:
        kw['weekday'], wd_mb = rand_weekday()
    if allow_yearday and rnd.random() < 0.08:
        kw[rnd.choice(['yearday', 'nlyearday'])] = rnd.choice(
            [rnd.randint(1, 366), rnd.randint(55, 65), 367, -3])
    for k, v in kw.items():
        if k == 'weekday':
            mb.append('weekday=%s' % wd_mb)
        elif floaty and k in ('years', 'months', 'days', 'weeks', 'hours',
                              'minutes', 'seconds', 'microseconds'):
            mb.append('%s=%s' % (k, fl(v)))
        else:
            mb.append('%s=%d' % (k, v))
    ctor = 'from_float' if floaty else 'new'
    call = '@relativedelta.RelativeDelta::%s(%s)' % (ctor, ', '.join(mb))
    try:
        py = relativedelta(**{k: (float(v) if floaty and k in ('years', 'months') else v)
                              for k, v in kw.items()})
    except ValueError:
        py = 'ValueError'
    return py, call


def rand_valid_rd(**k):
    while True:
        py, mb = rand_rd(**k)
        if not isinstance(py, str):
            return py, mb


# ---------------------------------------------------------------------------
# construction: repr, normalized, weeks, has_time, bool

for chunk in range(4):
    lines = []
    for _ in range(80):
        py, mb = rand_rd()
        if isinstance(py, str):
            lines.append('check_ctor_error(() => %s, %s)' % (mb, mbt_str(py)))
            continue
        lines.append('check_ctor(%s, %s, normalized=%s, weeks=%d, has_time=%s, truthy=%s)' % (
            mb, mbt_str(repr(py)), mbt_str(repr(py.normalized())), py.weeks,
            'true' if py._has_time else 'false', 'true' if bool(py) else 'false'))
    emit('python: construction %d' % chunk, lines)

# fractional years/months
lines = []
for v in [1.5, -0.5, 2.25]:
    for k in ['years', 'months']:
        lines.append('check_ctor_error(() => @relativedelta.RelativeDelta::from_float(%s=%s), "ValueError")' % (k, fl(v)))
emit('python: fractional years/months', lines)

# repr float formatting ({:+g})
lines = []
specials = [0.5, 1.25, 9.22, 1e-05, 0.0001, 123456.0, 1234567.0, 999999.5, 999999.4,
            0.1, 1.0 / 3, -2.0 / 3, 1e16, 1.5e-7, 12345.65, 0.000123456789]
for v in specials + [rnd.uniform(-1e7, 1e7) for _ in range(30)] + [rnd.uniform(-1, 1) * 10 ** rnd.randint(-8, 12) for _ in range(30)]:
    py = relativedelta(days=v)
    lines.append('check_repr(@relativedelta.RelativeDelta::from_float(days=%s), %s)' % (fl(v), mbt_str(repr(py))))
for v in [10 ** 6, 10 ** 7, 123456789, -987654321]:
    py = relativedelta(days=v)
    lines.append('check_repr(@relativedelta.RelativeDelta::new(days=%d), %s)' % (v, mbt_str(repr(py))))
emit('python: repr float formatting', lines)

# normalized with awkward fractions
lines = []
for _ in range(80):
    kw = {}
    for k, s in [('days', 10), ('hours', 30), ('minutes', 100), ('seconds', 100), ('microseconds', 2e6)]:
        if rnd.random() < 0.6:
            kw[k] = rnd.uniform(-s, s)
    py = relativedelta(**kw)
    mb = ', '.join('%s=%s' % (k, fl(v)) for k, v in kw.items())
    lines.append('check_normalized(@relativedelta.RelativeDelta::from_float(%s), %s)' % (mb, mbt_str(repr(py.normalized()))))
emit('python: normalized', lines)

# ---------------------------------------------------------------------------
# application to dates and datetimes

EDGE_DATES = [
    date(2003, 1, 31), date(2004, 1, 31), date(2000, 2, 29), date(2004, 2, 29),
    date(2001, 2, 28), date(1900, 2, 28), date(2000, 3, 1), date(1999, 12, 31),
    date(2000, 1, 1), date(2003, 9, 17), date(1, 1, 1), date(1, 1, 31),
    date(9999, 12, 31), date(9999, 1, 31), date(2020, 4, 30), date(2021, 5, 31),
]


def rand_date():
    if rnd.random() < 0.6:
        return rnd.choice(EDGE_DATES)
    o = rnd.randint(date(1800, 1, 1).toordinal(), date(2200, 1, 1).toordinal())
    return date.fromordinal(o)


def rand_datetime():
    d = rand_date()
    if rnd.random() < 0.3:
        return datetime(d.year, d.month, d.day)
    return datetime(d.year, d.month, d.day, rnd.randint(0, 23), rnd.randint(0, 59),
                    rnd.randint(0, 59), rnd.choice([0, rnd.randint(0, 999999)]))


def mb_date(d):
    return 'date(%d, %d, %d)' % (d.year, d.month, d.day)


def mb_dt(d):
    return 'pdt(%d, %d, %d, %d, %d, %d, %d)' % (d.year, d.month, d.day, d.hour, d.minute, d.second, d.microsecond)


for chunk in range(5):
    lines = []
    for _ in range(80):
        py, mb = rand_valid_rd()
        if rnd.random() < 0.5:
            base = rand_date()
            mbase = mb_date(base)
            fn = 'check_apply_date'
        else:
            base = rand_datetime()
            mbase = mb_dt(base)
            fn = 'check_apply_dt'
        add = outcome(lambda: base + py)
        sub = outcome(lambda: base - py)
        lines.append('%s(%s, %s, add=%s, sub=%s)' % (fn, mb, mbase, mbt_str(add), mbt_str(sub)))
    emit('python: apply %d' % chunk, lines)

# month-end / leap-year focused application
lines = []
for base in EDGE_DATES:
    for kw in [dict(months=1), dict(months=-1), dict(years=1), dict(years=-1), dict(months=12),
               dict(years=4), dict(leapdays=1, month=3), dict(yearday=60), dict(nlyearday=60),
               dict(yearday=366), dict(day=31, weekday=weekdays[4](-1)), dict(weekday=weekdays[0](0)),
               dict(days=1.5), dict(days=-0.25), dict(weeks=0.5), dict(hours=36)]:
        py = relativedelta(**kw)
        parts = []
        floaty = any(isinstance(v, float) for v in kw.values())
        for k, v in kw.items():
            if k == 'weekday':
                parts.append('weekday=@relativedelta.%s.nth(Some(%d))' % (WD[v.weekday], v.n))
            elif isinstance(v, float):
                parts.append('%s=%s' % (k, fl(v)))
            else:
                parts.append('%s=%d' % (k, v))
        call = '@relativedelta.RelativeDelta::%s(%s)' % ('from_float' if floaty else 'new', ', '.join(parts))
        lines.append('check_apply_date(%s, %s, add=%s, sub=%s)' % (
            call, mb_date(base), mbt_str(outcome(lambda: base + py)), mbt_str(outcome(lambda: base - py))))
emit('python: apply month ends and leap years', lines)

# fractional relative fields: exercises CPython's (C) timedelta float
# accumulation and its half-even rounding of the sub-microsecond leftover
lines = []
base = datetime(2009, 9, 3, 12, 0, 0, 500000)
for _ in range(150):
    kw = {}
    for k, s in [('days', 10), ('hours', 30), ('minutes', 100), ('seconds', 100), ('microseconds', 2e6)]:
        if rnd.random() < 0.6:
            kw[k] = round(rnd.uniform(-s, s), rnd.choice([1, 2, 3, 6, 9]))
    if rnd.random() < 0.3:
        kw['microseconds'] = rnd.randint(-2000000, 2000000) + 0.5
    py = relativedelta(**kw)
    mb = ', '.join('%s=%s' % (k, fl(v)) for k, v in kw.items())
    lines.append('check_apply_dt(@relativedelta.RelativeDelta::from_float(%s), %s, add=%s, sub=%s)' % (
        mb, mb_dt(base), mbt_str(outcome(lambda: base + py)), mbt_str(outcome(lambda: base - py))))
emit('python: apply fractional fields', lines)

# ---------------------------------------------------------------------------
# relativedelta(dt1, dt2)

lines = []
for _ in range(150):
    kind = rnd.random()
    if kind < 0.35:
        a, b = rand_date(), rand_date()
        lines.append('check_between_dates(%s, %s, %s)' % (mb_date(a), mb_date(b), mbt_str(repr(relativedelta(a, b)))))
    elif kind < 0.5:
        a, b = rand_date(), rand_datetime()
        if rnd.random() < 0.5:
            lines.append('check_between(%s.to_datetime(), %s, %s)' % (mb_date(a), mb_dt(b), mbt_str(repr(relativedelta(a, b)))))
        else:
            lines.append('check_between(%s, %s.to_datetime(), %s)' % (mb_dt(b), mb_date(a), mbt_str(repr(relativedelta(b, a)))))
    else:
        a, b = rand_datetime(), rand_datetime()
        if rnd.random() < 0.3:
            # close together
            b = a + timedelta(seconds=rnd.randint(-10 ** 7, 10 ** 7), microseconds=rnd.randint(-10 ** 6, 10 ** 6))
        lines.append('check_between(%s, %s, %s)' % (mb_dt(a), mb_dt(b), mbt_str(repr(relativedelta(a, b)))))
emit('python: between', lines)

lines = []
for _ in range(30):
    a, b = rand_datetime(), rand_datetime()
    oa, ob = rnd.randint(-50000, 50000), rnd.randint(-50000, 50000)
    ta, tb = tz.tzoffset(None, oa), tz.tzoffset(None, ob)
    try:
        r = repr(relativedelta(a.replace(tzinfo=ta), b.replace(tzinfo=tb)))
    except (ValueError, OverflowError) as e:
        r = type(e).__name__
    lines.append('check_between_aware(%s, %d, %s, %d, %s)' % (mb_dt(a), oa, mb_dt(b), ob, mbt_str(r)))
emit('python: between aware', lines)

# ---------------------------------------------------------------------------
# arithmetic

lines = []
for _ in range(120):
    pa, ma = rand_valid_rd(allow_yearday=False)
    pb, mbb = rand_valid_rd(allow_yearday=False)
    f = rnd.choice([2, 3, -1, 28, 0.5, -1.5, 1.0 / 3, rnd.uniform(-10, 10)])
    lines.append('check_arith(%s, %s, %s, add=%s, sub=%s, neg=%s, abs=%s, mul=%s, div=%s, eq=%s)' % (
        ma, mbb, fl(f), mbt_str(repr(pa + pb)), mbt_str(repr(pa - pb)), mbt_str(repr(-pa)),
        mbt_str(repr(abs(pa))), mbt_str(repr(pa * f)), mbt_str(repr(pa / f)),
        'true' if pa == pb else 'false'))
emit('python: arithmetic', lines)

lines = []
for _ in range(40):
    pa, ma = rand_valid_rd(allow_yearday=False)
    td = timedelta(days=rnd.randint(-500, 500), seconds=rnd.randint(0, 86399), microseconds=rnd.randint(0, 999999))
    lines.append('check_add_timedelta(%s, @datetime.TimeDelta::new(days=%d, seconds=%d, microseconds=%d), %s)' % (
        ma, td.days, td.seconds, td.microseconds, mbt_str(repr(pa + td))))
emit('python: add timedelta', lines)

# equality with weekday n variants
lines = []
ns = [None, 0, 1, -1, 2]
for k in range(2):
    for n1 in ns:
        for n2 in ns:
            a = relativedelta(days=1, weekday=weekdays[0](n1))
            b = relativedelta(days=1, weekday=weekdays[k](n2))

            def wmb(kk, n):
                return '@relativedelta.%s' % WD[kk] if n is None else '@relativedelta.%s.nth(Some(%d))' % (WD[kk], n)
            lines.append('check_eq(@relativedelta.RelativeDelta::new(days=1, weekday=%s), @relativedelta.RelativeDelta::new(days=1, weekday=%s), %s)' % (
                wmb(0, n1), wmb(k, n2), 'true' if a == b else 'false'))
emit('python: equality with weekdays', lines)

sys.stdout.write('\n'.join(out))
